;; -*- mode:elisp; coding: utf-8  -*-
;; Copyright 2017, Soós Péter Levente
;; Licensed under the MIT license.

;;;; Various custom variables
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#2d3743" "#ff4242" "#74af68" "#dbdb95" "#34cae2" "#008b8b" "#00ede1" "#e1e1e0"])
 '(auto-revert-verbose nil)
 '(backup-by-copying t)
 '(backup-directory-alist (\` (("." . "~/.saves"))))
 '(blink-cursor-mode nil)
 '(browse-url-browser-function (quote w3m-browse-url-dwim))
 '(browse-url-text-browser "w3m")
 '(column-number-mode t)
 '(company-auto-complete t)
 '(company-auto-complete-chars nil)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 2)
 '(company-selection-wrap-around t)
 '(company-tooltip-limit 20)
 '(css-indent-offset 2)
 '(custom-safe-themes
   (quote
    ("67255a169c47d3a3c9742647e202fccc8146f9c0cc4cbe37e2111ac73016b581" "d38d15985c7e1e6928289e1b6fbfa09458ba990d6294553fbc18b925b6a1f41b" "9edc9a00a7f947a81d11c367cc5296614917eb290ceca62ac19735939a477d97" default)))
 '(delete-old-versions t)
 '(delete-selection-mode t)
 '(global-hl-line-mode t)
 '(global-visual-line-mode t)
 '(global-yascroll-bar-mode t)
 '(glyphless-char-display-control
   (quote
    ((format-control . thin-space)
     (no-font . thin-space))))
 '(helm-follow-mode-persistent t)
 '(helm-source-names-using-follow (quote ("Occur")))
 '(helm-split-window-default-side (quote right))
 '(highlight-symbol-idle-delay 0.5)
 '(highlight-symbol-on-navigation-p t)
 '(hl-paren-background-colors (quote ignore))
 '(hl-paren-colors (quote ("white smoke")))
 '(idle-highlight-exceptions (quote ("end")))
 '(idle-highlight-idle-time 0.1)
 '(ido-mode t nil (ido))
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message "")
 '(js-indent-level 2)
 '(js-switch-indent-offset 2)
 '(kept-new-versions 6)
 '(kept-old-versions 2)
 '(linum-delay t)
 '(linum-format (quote dynamic))
 '(menu-bar-mode nil)
 '(neo-cwd-line-style (quote text))
 '(neo-force-change-root t)
 '(neo-smart-open t)
 '(neo-theme (quote ascii))
 '(org-edit-src-persistent-message nil)
 '(org-file-apps
   (quote
    ((auto-mode . emacs)
     ("\\.mm\\'" . default)
     ("\\.x?html?\\'" . default)
     ("\\.pdf\\'" . emacs))))
 '(org-latex-default-packages-alist
   (quote
    (("" "color" nil)
     ("" "listings" nil)
     ("" "fixltx2e" nil)
     ("" "graphicx" t)
     ("" "longtable" nil)
     ("" "float" nil)
     ("" "wrapfig" nil)
     ("" "rotating" nil)
     ("normalem" "ulem" t)
     ("" "amsmath" t)
     ("" "textcomp" t)
     ("" "marvosym" t)
     ("" "wasysym" t)
     ("" "amssymb" t)
     ("" "hyperref" nil)
     "\\tolerance=1000")))
 '(org-latex-listings t)
 '(org-latex-pdf-process
   (quote
    ("xelatex -shell-escape -interaction nonstopmode -output-directory %o %f" "xelatex -shell-escape -interaction nonstopmode -output-directory %o %f" "xelatex -shell-escape -interaction nonstopmode -output-directory %o %f")) t)
 '(org-src-ask-before-returning-to-edit-buffer nil)
 '(org-src-fontify-natively t)
 '(org-src-preserve-indentation t)
 '(org-src-window-setup (quote other-window))
 '(org-startup-with-latex-preview t)
 '(overwrite-selection-mode t)
 '(package-selected-packages
   (quote
    (yascroll sublimity highlight highlight-symbol nlinum-hl fountain-mode ws-trim nlinum irfc nodejs-repl pdf-tools js-doc web-beautify writeroom-mode idle-highlight-mode aozora-view win-switch helm-ag parinfer neotree visual-fill-column highlight-quoted latex-preview-pane header2 elfeed markdown-mode slime magit w3m slime-company quack paredit js2-mode highlight-parentheses geiser dumb-jump dart-mode common-lisp-snippets auto-yasnippet ac-slime)))
 '(pdf-latex-command "xelatex")
 '(safe-local-variable-values
   (quote
    ((Base . 10)
     (Package . CL-PPCRE)
     (Syntax . COMMON-LISP)
     (copyright . MIT)
     (author . soos-peter-levente)
     (author . spl)
     (license . MIT))))
 '(scroll-bar-mode -1)
 '(select-enable-clipboard t)
 '(show-paren-delay 0)
 '(show-paren-mode t)
 '(show-paren-priority 10)
 '(show-paren-style (quote parenthesis))
 '(show-paren-when-point-in-periphery t)
 '(show-paren-when-point-inside-paren nil)
 '(show-trailing-whitespace t)
 '(slime-company-after-completion nil)
 '(slime-company-complete-in-comments-and-strings t)
 '(slime-company-completion (quote fuzzy))
 '(slime-kill-without-query-p t)
 '(split-height-threshold nil)
 '(split-width-threshold 160)
 '(tool-bar-mode nil)
 '(truncate-lines t)
 '(version-control t)
 '(w3m-confirm-leaving-secure-page nil)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-tests-directory "/tmp/tests/")
 '(win-switch-idle-time 1.5)
 '(win-switch-window-threshold 0)
 '(yas-triggers-in-field t)
 '(yascroll:delay-to-hide 1.0))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-scrollbar-fg ((t (:background "dodger blue"))))
 '(company-tooltip ((t (:background "light steel blue" :foreground "dim gray"))))
 '(company-tooltip-common ((t (:foreground "black"))))
 '(font-lock-builtin-face ((t (:foreground "light sky blue"))))
 '(font-lock-comment-face ((t (:foreground "dim gray"))))
 '(font-lock-constant-face ((t (:foreground "light sky blue"))))
 '(font-lock-doc-face ((t (:foreground "lawn green"))))
 '(font-lock-keyword-face ((t (:foreground "DeepSkyBlue1" :weight extra-bold))))
 '(font-lock-string-face ((t (:foreground "lawn green"))))
 '(font-lock-type-face ((t (:foreground "DeepSkyBlue1"))))
 '(helm-source-header ((t (:background "#22083397778B" :foreground "white" :weight bold :height 1.0))))
 '(highlight-symbol-face ((t (:foreground "dark gray"))))
 '(hl-line ((t (:background "gray18"))))
 '(hl-paren-face ((t (:background "dim gray" :foreground "white smoke"))) t)
 '(idle-highlight ((t (:foreground "dark gray"))))
 '(show-paren-match ((t (:background "dim gray" :foreground "white smoke"))))
 '(show-paren-match-expression ((t (:background "dim gray" :foreground "white smoke"))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(slime-repl-inputed-output-face ((t (:foreground "salmon"))))
 '(trailing-whitespace ((t (:background "gray18"))))
 '(yascroll:thumb-fringe ((t (:background "dodger blue" :foreground "dodger blue")))))
